### ISSUE TITLE
OpenTracing标准中文版

### ISSUE THREAD

**Issue by wu-sheng** [sfpprxy/OpenTracing-Semantic-Specification#1]
你好，OpenTracing的中文版本，已经在官方的仓库中提供。

请查看：https://github.com/opentracing-contrib/opentracing-specification-zh

欢迎你的参与到这份文档的翻译和改进中。我们共同维护统一的翻译版本。目前OpenTracing已经发布到1.1，同步的更新需要大家的共同努力。

**Comment by sfpprxy** [comment]
好的 谢谢通知
